"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode =
  | "tr"
  | "en"
  | "de"
  | "es"
  | "fr"
  | "it"
  | "ru"
  | "ar"
  | "zh-CN"
  | "ja"
  | "ko"
  | "pt"
  | "az"
  | "nl";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh-CN", name: "Chinese", nativeName: "简体中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan", flag: "🇦🇿" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
];

export const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  tr: {
    "nav.tools": "Araçlar",
    "nav.playground": "Playground",
    "nav.resources": "Kaynaklar",
    "nav.community": "Topluluk",
    "nav.explore": "Keşfet",
    "nav.blog": "Blog",
    "nav.about": "Hakkımızda",
    "nav.login": "Giriş Yap",
    "nav.register": "Üye Ol",
    "nav.dashboard": "Dashboard & Profil",
    "nav.publicProfile": "Kamuya Açık Profil",
    "nav.settings": "Ayarlar & Güvenlik",
    "nav.logout": "Çıkış Yap",
    "nav.langSelect": "Dil Seçimi",

    "hero.badge": "Kodla. Öğren. Geliş.",
    "hero.titlePrefix": "Geliştiriciler için",
    "hero.titleBreak": "her şey",
    "hero.titleHighlight": "burada.",
    "hero.subtitle": "Hey! Coder'z, geliştiricilerin üretkenliğini artıran araçlar, kaynaklar ve topluluk desteği sunar. Birlikte öğren, birlikte geliştir.",
    "hero.exploreBtn": "Hemen Keşfet",
    "hero.resourcesBtn": "Kaynaklara Göz At",
    "trust.label": "GELİŞTİRİCİLERİN GÜVENDİĞİ PLATFORM",

    "common.search": "Ara...",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.loading": "Yükleniyor...",
    "common.refresh": "Yenile",
    "common.viewProfile": "Profili Gör",
    "common.shareProfile": "Profili Paylaş",
    "common.copied": "Kopyalandı!",
    "common.founder": "Kurucu & Admin",
    "common.coFounder": "Kurucu Ortak & Admin",
    "common.developer": "Geliştirici",
    "common.backToTop": "Yukarı Çık",
    "common.apply": "Uygula",

    "explore.badge": "Geliştirici Topluluğu & Vitrini",
    "explore.titlePrefix": "Yetenekleri",
    "explore.titleHighlight": "Keşfet",
    "explore.description": "Hey Coder'z ekosistemindeki tüm geliştiricileri, kurucuları ve yeni katılan yetenekleri keşfedin, profillerini inceleyin.",
    "explore.totalMembers": "Toplam Üye",
    "explore.management": "Yönetim",
    "explore.searchPlaceholder": "İsim, @kullanıcı veya teknoloji ara (örn: React)...",
    "explore.filterAll": "Tüm Üyeler",
    "explore.filterAdmin": "Yönetim & Kurucular",
    "explore.filterNew": "Yeni Katılanlar",
    "explore.filterTopXp": "En Yüksek XP",
    "explore.notFound": "Kullanıcı Bulunamadı",
    "explore.notFoundDesc": "Arama kriterinize uygun bir geliştirici profili bulunamadı.",

    "footer.desc": "Geliştiricilerin üretkenliğini artıran araçlar, kaynaklar ve modern geliştirici ekosistemi platformu.",
    "footer.navigation": "Navigasyon",
    "footer.ecosystem": "Ekosistem",
    "footer.legal": "Yasal & Gizlilik",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları",
    "footer.cookies": "Çerez Politikası",
    "footer.copyright": "Tüm hakları saklıdır.",
  },

  en: {
    "nav.tools": "Tools",
    "nav.playground": "Playground",
    "nav.resources": "Resources",
    "nav.community": "Community",
    "nav.explore": "Explore",
    "nav.blog": "Blog",
    "nav.about": "About Us",
    "nav.login": "Sign In",
    "nav.register": "Sign Up",
    "nav.dashboard": "Dashboard & Profile",
    "nav.publicProfile": "Public Profile",
    "nav.settings": "Settings & Security",
    "nav.logout": "Log Out",
    "nav.langSelect": "Language",

    "hero.badge": "Code. Learn. Grow.",
    "hero.titlePrefix": "Everything for",
    "hero.titleBreak": "developers",
    "hero.titleHighlight": "is here.",
    "hero.subtitle": "Hey! Coder'z empowers developer productivity with essential tools, rich resources, and a vibrant community.",
    "hero.exploreBtn": "Explore Now",
    "hero.resourcesBtn": "Browse Resources",
    "trust.label": "TRUSTED DEVELOPER PLATFORM",

    "common.search": "Search...",
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.refresh": "Refresh",
    "common.viewProfile": "View Profile",
    "common.shareProfile": "Share Profile",
    "common.copied": "Copied!",
    "common.founder": "Founder & Admin",
    "common.coFounder": "Co-Founder & Admin",
    "common.developer": "Developer",
    "common.backToTop": "Back to Top",
    "common.apply": "Apply",

    "explore.badge": "Developer Community & Showcase",
    "explore.titlePrefix": "Discover",
    "explore.titleHighlight": "Talents",
    "explore.description": "Explore developers, founders, and emerging talents across the Hey Coder'z ecosystem.",
    "explore.totalMembers": "Total Members",
    "explore.management": "Management",
    "explore.searchPlaceholder": "Search by name, @username, or tech (e.g. React)...",
    "explore.filterAll": "All Members",
    "explore.filterAdmin": "Leadership & Founders",
    "explore.filterNew": "New Arrivals",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "No Users Found",
    "explore.notFoundDesc": "No developer profile matched your search criteria.",

    "footer.desc": "Tools, resources, and modern developer ecosystem platform empowering developer productivity.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Ecosystem",
    "footer.legal": "Legal & Privacy",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.copyright": "All rights reserved.",
  },

  de: {
    "nav.tools": "Werkzeuge",
    "nav.playground": "Playground",
    "nav.resources": "Ressourcen",
    "nav.community": "Community",
    "nav.explore": "Entdecken",
    "nav.blog": "Blog",
    "nav.about": "Über Uns",
    "nav.login": "Anmelden",
    "nav.register": "Registrieren",
    "nav.dashboard": "Dashboard & Profil",
    "nav.publicProfile": "Öffentliches Profil",
    "nav.settings": "Einstellungen & Sicherheit",
    "nav.logout": "Abmelden",
    "nav.langSelect": "Sprache",

    "hero.badge": "Coden. Lernen. Wachsen.",
    "hero.titlePrefix": "Alles für",
    "hero.titleBreak": "Entwickler",
    "hero.titleHighlight": "ist hier.",
    "hero.subtitle": "Hey! Coder'z steigert die Produktivität von Entwicklern mit nützlichen Tools, Ressourcen und Community-Support.",
    "hero.exploreBtn": "Jetzt Entdecken",
    "hero.resourcesBtn": "Ressourcen ansehen",
    "trust.label": "DIE BEWÄHRTE ENTWICKLER-PLATTFORM",

    "common.search": "Suchen...",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.loading": "Wird geladen...",
    "common.refresh": "Aktualisieren",
    "common.viewProfile": "Profil ansehen",
    "common.shareProfile": "Profil teilen",
    "common.copied": "Kopiert!",
    "common.founder": "Gründer & Admin",
    "common.coFounder": "Mitgründer & Admin",
    "common.developer": "Entwickler",
    "common.backToTop": "Nach oben",
    "common.apply": "Anwenden",

    "explore.badge": "Entwickler-Community & Vitrine",
    "explore.titlePrefix": "Talente",
    "explore.titleHighlight": "Entdecken",
    "explore.description": "Entdecken Sie Entwickler, Gründer und Talente im Hey Coder'z-Ökosystem.",
    "explore.totalMembers": "Mitglieder Gesamt",
    "explore.management": "Leitung",
    "explore.searchPlaceholder": "Name, @Benutzer oder Technologie suchen...",
    "explore.filterAll": "Alle Mitglieder",
    "explore.filterAdmin": "Leitung & Gründer",
    "explore.filterNew": "Neu Beigetreten",
    "explore.filterTopXp": "Höchste XP",
    "explore.notFound": "Keine Benutzer gefunden",
    "explore.notFoundDesc": "Kein Entwicklerprofil entspricht Ihren Kriterien.",

    "footer.desc": "Moderne Entwicklerplattform für Tools, Ressourcen und Gemeinschaft.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Ökosystem",
    "footer.legal": "Rechtliches & Datenschutz",
    "footer.privacy": "Datenschutzerklärung",
    "footer.terms": "Nutzungsbedingungen",
    "footer.cookies": "Cookie-Richtlinie",
    "footer.copyright": "Alle Rechte vorbehalten.",
  },

  es: {
    "nav.tools": "Herramientas",
    "nav.playground": "Playground",
    "nav.resources": "Recursos",
    "nav.community": "Comunidad",
    "nav.explore": "Explorar",
    "nav.blog": "Blog",
    "nav.about": "Sobre Nosotros",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Registrarse",
    "nav.dashboard": "Panel y Perfil",
    "nav.publicProfile": "Perfil Público",
    "nav.settings": "Ajustes y Seguridad",
    "nav.logout": "Cerrar Sesión",
    "nav.langSelect": "Idioma",

    "hero.badge": "Programa. Aprende. Crece.",
    "hero.titlePrefix": "Todo para",
    "hero.titleBreak": "desarrolladores",
    "hero.titleHighlight": "está aquí.",
    "hero.subtitle": "Hey! Coder'z impulsa la productividad de los desarrolladores con herramientas modernas, recursos y comunidad.",
    "hero.exploreBtn": "Explorar Ahora",
    "hero.resourcesBtn": "Ver Recursos",
    "trust.label": "PLATAFORMA DE CONFIANZA PARA DESARROLLADORES",

    "common.search": "Buscar...",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.refresh": "Actualizar",
    "common.viewProfile": "Ver Perfil",
    "common.shareProfile": "Compartir Perfil",
    "common.copied": "¡Copiado!",
    "common.founder": "Fundador y Admin",
    "common.coFounder": "Cofundador y Admin",
    "common.developer": "Desarrollador",
    "common.backToTop": "Volver arriba",
    "common.apply": "Aplicar",

    "explore.badge": "Comunidad de Desarrolladores",
    "explore.titlePrefix": "Descubre",
    "explore.titleHighlight": "Talentos",
    "explore.description": "Explora desarrolladores, fundadores y nuevos talentos en el ecosistema Hey Coder'z.",
    "explore.totalMembers": "Miembros Totales",
    "explore.management": "Gestión",
    "explore.searchPlaceholder": "Buscar por nombre, @usuario o tecnología...",
    "explore.filterAll": "Todos los Miembros",
    "explore.filterAdmin": "Líderes y Fundadores",
    "explore.filterNew": "Nuevas Incorporaciones",
    "explore.filterTopXp": "Más XP",
    "explore.notFound": "Usuario no encontrado",
    "explore.notFoundDesc": "No se encontraron perfiles con esos criterios.",

    "footer.desc": "Herramientas y recursos que impulsan la productividad del desarrollador.",
    "footer.navigation": "Navegación",
    "footer.ecosystem": "Ecosistema",
    "footer.legal": "Legal y Privacidad",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.cookies": "Política de Cookies",
    "footer.copyright": "Todos los derechos reservados.",
  },

  fr: {
    "nav.tools": "Outils",
    "nav.playground": "Playground",
    "nav.resources": "Ressources",
    "nav.community": "Communauté",
    "nav.explore": "Explorer",
    "nav.blog": "Blog",
    "nav.about": "À Propos",
    "nav.login": "Connexion",
    "nav.register": "S'inscrire",
    "nav.dashboard": "Tableau de bord",
    "nav.publicProfile": "Profil Public",
    "nav.settings": "Paramètres",
    "nav.logout": "Déconnexion",
    "nav.langSelect": "Langue",

    "hero.badge": "Coder. Apprendre. Évoluer.",
    "hero.titlePrefix": "Tout pour les",
    "hero.titleBreak": "développeurs",
    "hero.titleHighlight": "est ici.",
    "hero.subtitle": "Hey! Coder'z augmente la productivité des développeurs grâce à des outils essentiels et une communauté active.",
    "hero.exploreBtn": "Explorer Maintenant",
    "hero.resourcesBtn": "Voir les Ressources",
    "trust.label": "LA PLATEFORME DE CONFIANCE DES DÉVELOPPEURS",

    "common.search": "Rechercher...",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.refresh": "Actualiser",
    "common.viewProfile": "Voir le profil",
    "common.shareProfile": "Partager le profil",
    "common.copied": "Copié !",
    "common.founder": "Fondateur & Admin",
    "common.coFounder": "Co-fondateur & Admin",
    "common.developer": "Développeur",
    "common.backToTop": "Haut de page",
    "common.apply": "Appliquer",

    "explore.badge": "Vitrine des Développeurs",
    "explore.titlePrefix": "Découvrir les",
    "explore.titleHighlight": "Talents",
    "explore.description": "Explorez les développeurs et talents de l'écosystème Hey Coder'z.",
    "explore.totalMembers": "Total Membres",
    "explore.management": "Direction",
    "explore.searchPlaceholder": "Rechercher nom, @utilisateur ou techno...",
    "explore.filterAll": "Tous les Membres",
    "explore.filterAdmin": "Direction & Fondateurs",
    "explore.filterNew": "Nouveaux Arrivants",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "Aucun utilisateur trouvé",
    "explore.notFoundDesc": "Aucun profil ne correspond à vos critères.",

    "footer.desc": "Plateforme moderne pour développeurs.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Écosystème",
    "footer.legal": "Légal & Confidentialité",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.cookies": "Politique des Cookies",
    "footer.copyright": "Tous droits réservés.",
  },

  it: {
    "nav.tools": "Strumenti",
    "nav.playground": "Playground",
    "nav.resources": "Risorse",
    "nav.community": "Community",
    "nav.explore": "Esplora",
    "nav.blog": "Blog",
    "nav.about": "Chi Siamo",
    "nav.login": "Accedi",
    "nav.register": "Registrati",
    "nav.dashboard": "Dashboard",
    "nav.publicProfile": "Profilo Pubblico",
    "nav.settings": "Impostazioni",
    "nav.logout": "Esci",
    "nav.langSelect": "Lingua",

    "hero.badge": "Programma. Impara. Cresci.",
    "hero.titlePrefix": "Tutto per gli",
    "hero.titleBreak": "sviluppatori",
    "hero.titleHighlight": "è qui.",
    "hero.subtitle": "Hey! Coder'z potenzia la produttività degli sviluppatori con strumenti all'avanguardia e supporto comunitario.",
    "hero.exploreBtn": "Esplora Ora",
    "hero.resourcesBtn": "Sfoglia Risorse",
    "trust.label": "LA PIATTAFORMA DI CUI GLI SVILUPPATORI SI FIDANO",

    "common.search": "Cerca...",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.delete": "Elimina",
    "common.edit": "Modifica",
    "common.loading": "Caricamento...",
    "common.refresh": "Aggiorna",
    "common.viewProfile": "Vedi Profilo",
    "common.shareProfile": "Condividi Profilo",
    "common.copied": "Copiato!",
    "common.founder": "Fondatore & Admin",
    "common.coFounder": "Co-fondatore & Admin",
    "common.developer": "Sviluppatore",
    "common.backToTop": "Torna su",
    "common.apply": "Applica",

    "explore.badge": "Community di Sviluppatori",
    "explore.titlePrefix": "Scopri i",
    "explore.titleHighlight": "Talenti",
    "explore.description": "Esplora programmatori e talenti nell'ecosistema Hey Coder'z.",
    "explore.totalMembers": "Membri Totali",
    "explore.management": "Gestione",
    "explore.searchPlaceholder": "Cerca per nome, @username o tecnologia...",
    "explore.filterAll": "Tutti i Membri",
    "explore.filterAdmin": "Leader & Fondatori",
    "explore.filterNew": "Nuovi Arrivi",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "Nessun utente trovato",
    "explore.notFoundDesc": "Nessun profilo corrisponde alla ricerca.",

    "footer.desc": "Piattaforma moderna per sviluppatori e programmatori.",
    "footer.navigation": "Navigazione",
    "footer.ecosystem": "Ecosistema",
    "footer.legal": "Legale & Privacy",
    "footer.privacy": "Informativa sulla Privacy",
    "footer.terms": "Termini di Servizio",
    "footer.cookies": "Politica sui Cookie",
    "footer.copyright": "Tutti i diritti riservati.",
  },

  ru: {
    "nav.tools": "Инструменты",
    "nav.playground": "Песочница",
    "nav.resources": "Ресурсы",
    "nav.community": "Сообщество",
    "nav.explore": "Обзор",
    "nav.blog": "Блог",
    "nav.about": "О нас",
    "nav.login": "Войти",
    "nav.register": "Регистрация",
    "nav.dashboard": "Панель и Профиль",
    "nav.publicProfile": "Публичный Профиль",
    "nav.settings": "Настройки",
    "nav.logout": "Выйти",
    "nav.langSelect": "Язык",

    "hero.badge": "Кодируй. Учись. Развивайся.",
    "hero.titlePrefix": "Всё для",
    "hero.titleBreak": "разработчиков",
    "hero.titleHighlight": "здесь.",
    "hero.subtitle": "Hey! Coder'z повышает продуктивность разработчиков благодаря инструментам, ресурсам и сильному сообществу.",
    "hero.exploreBtn": "Исследовать сейчас",
    "hero.resourcesBtn": "Смотреть ресурсы",
    "trust.label": "ПЛАТФОРМА, КОТОРОЙ ДОВЕРЯЮТ РАЗРАБОТЧИКИ",

    "common.search": "Поиск...",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Изменить",
    "common.loading": "Загрузка...",
    "common.refresh": "Обновить",
    "common.viewProfile": "Смотреть профиль",
    "common.shareProfile": "Поделиться профилем",
    "common.copied": "Скопировано!",
    "common.founder": "Основатель и Админ",
    "common.coFounder": "Сооснователь и Админ",
    "common.developer": "Разработчик",
    "common.backToTop": "Наверх",
    "common.apply": "Применить",

    "explore.badge": "Сообщество разработчиков",
    "explore.titlePrefix": "Откройте",
    "explore.titleHighlight": "Таланты",
    "explore.description": "Исследуйте разработчиков и основателей в экосистеме Hey Coder'z.",
    "explore.totalMembers": "Всего участников",
    "explore.management": "Руководство",
    "explore.searchPlaceholder": "Поиск по имени, @username или стеку...",
    "explore.filterAll": "Все участники",
    "explore.filterAdmin": "Основатели и Админы",
    "explore.filterNew": "Новые участники",
    "explore.filterTopXp": "Топ по XP",
    "explore.notFound": "Пользователи не найдены",
    "explore.notFoundDesc": "По вашему запросу профили не найдены.",

    "footer.desc": "Инструменты и ресурсы для разработчиков.",
    "footer.navigation": "Навигация",
    "footer.ecosystem": "Экосистема",
    "footer.legal": "Правовая информация",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования",
    "footer.cookies": "Политика файлов cookie",
    "footer.copyright": "Все права защищены.",
  },

  ar: {
    "nav.tools": "الأدوات",
    "nav.playground": "ساحة التجربة",
    "nav.resources": "المصادر",
    "nav.community": "المجتمع",
    "nav.explore": "استكشف",
    "nav.blog": "المدونة",
    "nav.about": "معلومات عنا",
    "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب",
    "nav.dashboard": "لوحة التحكم",
    "nav.publicProfile": "الملف العام",
    "nav.settings": "الإعدادات",
    "nav.logout": "تسجيل الخروج",
    "nav.langSelect": "اللغة",

    "hero.badge": "برمج. تعلّم. تطوّر.",
    "hero.titlePrefix": "كل ما يحتاجه",
    "hero.titleBreak": "المطورون",
    "hero.titleHighlight": "هنا.",
    "hero.subtitle": "منصة Hey! Coder'z تزيد من إنتاجية المطورين بأحدث الأدوات والمصادر والمجتمع البرمجي.",
    "hero.exploreBtn": "استكشف الآن",
    "hero.resourcesBtn": "تصفح المصادر",
    "trust.label": "المنصة الموثوقة من قِبل المطورين",

    "common.search": "بحث...",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.loading": "جار التحميل...",
    "common.refresh": "تحديث",
    "common.viewProfile": "عرض الملف",
    "common.shareProfile": "مشاركة الملف",
    "common.copied": "تم النسخ!",
    "common.founder": "المؤسس والمسؤول",
    "common.coFounder": "شريك مؤسس ومسؤول",
    "common.developer": "مطور",
    "common.backToTop": "للأعلى",
    "common.apply": "تطبيق",

    "explore.badge": "مجتمع المطورين والمواهب",
    "explore.titlePrefix": "اكتشف",
    "explore.titleHighlight": "المواهب",
    "explore.description": "استكشف المطورين والمؤسسين والمواهب في مجتمع Hey Coder'z.",
    "explore.totalMembers": "إجمالي الأعضاء",
    "explore.management": "الإدارة",
    "explore.searchPlaceholder": "ابحث بالاسم أو التقنية...",
    "explore.filterAll": "جميع الأعضاء",
    "explore.filterAdmin": "الإدارة والمؤسسون",
    "explore.filterNew": "الأعضاء الجدد",
    "explore.filterTopXp": "الأعلى نقاطاً",
    "explore.notFound": "لم يتم العثور على مستخدمين",
    "explore.notFoundDesc": "لا توجد نتائج مطابقة لبحثك.",

    "footer.desc": "منصة شاملة لزيادة إنتاجية المطورين والمبرمجين.",
    "footer.navigation": "التنقل",
    "footer.ecosystem": "المنظومة",
    "footer.legal": "الشروط والخصوصية",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.cookies": "سياسة ملفات تعريف الارتباط",
    "footer.copyright": "جميع الحقوق محفوظة.",
  },

  "zh-CN": {
    "nav.tools": "开发者工具",
    "nav.playground": "演练场",
    "nav.resources": "开发资源",
    "nav.community": "开发者社区",
    "nav.explore": "发现人才",
    "nav.blog": "官方博客",
    "nav.about": "关于我们",
    "nav.login": "登录",
    "nav.register": "免费注册",
    "nav.dashboard": "控制台与个人中心",
    "nav.publicProfile": "公开主页",
    "nav.settings": "设置与安全",
    "nav.logout": "退出登录",
    "nav.langSelect": "语言切换",

    "hero.badge": "编码 · 学习 · 成长",
    "hero.titlePrefix": "专为开发者打造的",
    "hero.titleBreak": "一站式平台",
    "hero.titleHighlight": "就在这里",
    "hero.subtitle": "Hey! Coder'z 提供强大的在线开发者工具、精选技术资源与活跃开发者社区，全方位提升编程效率。",
    "hero.exploreBtn": "立即探索",
    "hero.resourcesBtn": "浏览资源库",
    "trust.label": "全球开发者信赖的生产力平台",

    "common.search": "搜索...",
    "common.save": "保存修改",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.loading": "加载中...",
    "common.refresh": "刷新",
    "common.viewProfile": "查看主页",
    "common.shareProfile": "分享主页",
    "common.copied": "已复制！",
    "common.founder": "创始人兼管理员",
    "common.coFounder": "联合创始人兼管理员",
    "common.developer": "开发者",
    "common.backToTop": "返回顶部",
    "common.apply": "应用",

    "explore.badge": "开发者社区与人才广场",
    "explore.titlePrefix": "发掘优秀",
    "explore.titleHighlight": "开发者人才",
    "explore.description": "探索 Hey Coder'z 生态系统中的所有优秀开发者、团队创始人与新兴技术人才。",
    "explore.totalMembers": "总注册成员",
    "explore.management": "管理团队",
    "explore.searchPlaceholder": "按姓名、用户名或技术栈搜索...",
    "explore.filterAll": "全部成员",
    "explore.filterAdmin": "管理团队与创始人",
    "explore.filterNew": "最新加入",
    "explore.filterTopXp": "经验值排行",
    "explore.notFound": "未找到相关开发者",
    "explore.notFoundDesc": "没有匹配当前筛选条件的开发者主页。",

    "footer.desc": "赋能现代开发者的高效工具箱、优质技术资源与开放社区。",
    "footer.navigation": "网站导航",
    "footer.ecosystem": "开发者生态",
    "footer.legal": "法律与隐私",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.cookies": "Cookie政策",
    "footer.copyright": "版权所有 · 保留所有权利。",
  },

  ja: {
    "nav.tools": "ツール",
    "nav.playground": "プレイグラウンド",
    "nav.resources": "リソース",
    "nav.community": "コミュニティ",
    "nav.explore": "見つける",
    "nav.blog": "ブログ",
    "nav.about": "私たちについて",
    "nav.login": "ログイン",
    "nav.register": "新規登録",
    "nav.dashboard": "ダッシュボード",
    "nav.publicProfile": "公開プロフィール",
    "nav.settings": "設定とセキュリティ",
    "nav.logout": "ログアウト",
    "nav.langSelect": "言語切り替え",

    "hero.badge": "コード。学び。成長。",
    "hero.titlePrefix": "開発者のためのすべてが",
    "hero.titleBreak": "ここに",
    "hero.titleHighlight": "揃っています。",
    "hero.subtitle": "Hey! Coder'z はエンジニアの生産性を高める開発ツール、リソース、コミュニティを提供します。",
    "hero.exploreBtn": "今すぐ探索",
    "hero.resourcesBtn": "リソースを見る",
    "trust.label": "開発者に選ばれる信頼のプラットフォーム",

    "common.search": "検索...",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.loading": "読み込み中...",
    "common.refresh": "更新",
    "common.viewProfile": "プロフィールを見る",
    "common.shareProfile": "プロフィールを共有",
    "common.copied": "コピーしました！",
    "common.founder": "創設者 & 管理者",
    "common.coFounder": "共同創設者 & 管理者",
    "common.developer": "開発者",
    "common.backToTop": "トップへ戻る",
    "common.apply": "適用",

    "explore.badge": "開発者コミュニティ",
    "explore.titlePrefix": "優れた才能を",
    "explore.titleHighlight": "見つける",
    "explore.description": "Hey Coder'z のクリエイターやエンジニアのプロフィールを探索しましょう。",
    "explore.totalMembers": "総メンバー数",
    "explore.management": "運営チーム",
    "explore.searchPlaceholder": "名前や技術名で検索...",
    "explore.filterAll": "すべてのメンバー",
    "explore.filterAdmin": "運営 & 創設者",
    "explore.filterNew": "新着メンバー",
    "explore.filterTopXp": "トップXP",
    "explore.notFound": "ユーザーが見つかりません",
    "explore.notFoundDesc": "条件に一致する開発者は見つかりませんでした。",

    "footer.desc": "開発者の生産性を向上させるエコシステム。",
    "footer.navigation": "ナビゲーション",
    "footer.ecosystem": "エコシステム",
    "footer.legal": "法的情報とプライバシー",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.cookies": "クッキーポリシー",
    "footer.copyright": "無断転載を禁じます。",
  },

  ko: {
    "nav.tools": "개발 도구",
    "nav.playground": "플레이그라운드",
    "nav.resources": "개발 리소스",
    "nav.community": "커뮤니티",
    "nav.explore": "탐색",
    "nav.blog": "블로그",
    "nav.about": "소개",
    "nav.login": "로그인",
    "nav.register": "회원가입",
    "nav.dashboard": "대시보드",
    "nav.publicProfile": "공개 프로필",
    "nav.settings": "설정 및 보안",
    "nav.logout": "로그아웃",
    "nav.langSelect": "언어 선택",

    "hero.badge": "코딩하고. 배우고. 성장하세요.",
    "hero.titlePrefix": "개발자를 위한 모든 것이",
    "hero.titleBreak": "바로 여기에",
    "hero.titleHighlight": "있습니다.",
    "hero.subtitle": "Hey! Coder'z는 개발자의 생산성을 극대화하는 강력한 온라인 도구, 학습 리소스 및 개발자 커뮤니티를 제공합니다.",
    "hero.exploreBtn": "지금 탐색하기",
    "hero.resourcesBtn": "리소스 둘러보기",
    "trust.label": "개발자가 신뢰하는 생산성 플랫폼",

    "common.search": "검색...",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.delete": "삭제",
    "common.edit": "수정",
    "common.loading": "로딩 중...",
    "common.refresh": "새로고침",
    "common.viewProfile": "프로필 보기",
    "common.shareProfile": "프로필 공유",
    "common.copied": "복사되었습니다!",
    "common.founder": "설립자 & 관리자",
    "common.coFounder": "공동 설립자 & 관리자",
    "common.developer": "개발자",
    "common.backToTop": "맨 위로",
    "common.apply": "적용",

    "explore.badge": "개발자 커뮤니티 & 쇼케이스",
    "explore.titlePrefix": "뛰어난 인재를",
    "explore.titleHighlight": "탐색하세요",
    "explore.description": "Hey Coder'z 생태계의 모든 개발자, 설립자 및 새로운 인재를 만나보세요.",
    "explore.totalMembers": "총 회원 수",
    "explore.management": "운영진",
    "explore.searchPlaceholder": "이름, @아이디 또는 기술 검색...",
    "explore.filterAll": "전체 회원",
    "explore.filterAdmin": "운영진 & 설립자",
    "explore.filterNew": "신규 가입",
    "explore.filterTopXp": "최고 경험치",
    "explore.notFound": "사용자를 찾을 수 없습니다",
    "explore.notFoundDesc": "검색 조건과 일치하는 개발자 프로필이 없습니다.",

    "footer.desc": "개발자 생산성을 향상시키는 현대적인 도구와 커뮤니티 플랫폼.",
    "footer.navigation": "내비게이션",
    "footer.ecosystem": "생태계",
    "footer.legal": "법적 고지 & 개인정보",
    "footer.privacy": "개인정보 처리방침",
    "footer.terms": "이용약관",
    "footer.cookies": "쿠키 정책",
    "footer.copyright": "모든 권리 보유.",
  },

  pt: {
    "nav.tools": "Ferramentas",
    "nav.playground": "Playground",
    "nav.resources": "Recursos",
    "nav.community": "Comunidade",
    "nav.explore": "Explorar",
    "nav.blog": "Blog",
    "nav.about": "Sobre Nós",
    "nav.login": "Entrar",
    "nav.register": "Cadastrar",
    "nav.dashboard": "Painel e Perfil",
    "nav.publicProfile": "Perfil Público",
    "nav.settings": "Configurações",
    "nav.logout": "Sair",
    "nav.langSelect": "Idioma",

    "hero.badge": "Programe. Aprenda. Evolua.",
    "hero.titlePrefix": "Tudo para",
    "hero.titleBreak": "desenvolvedores",
    "hero.titleHighlight": "está aqui.",
    "hero.subtitle": "Hey! Coder'z potencializa a produtividade dos desenvolvedores com ferramentas essenciais e suporte comunitário.",
    "hero.exploreBtn": "Explorar Agora",
    "hero.resourcesBtn": "Ver Recursos",
    "trust.label": "PLATAFORMA CONFIÁVEL PARA DESENVOLVEDORES",

    "common.search": "Pesquisar...",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.loading": "Carregando...",
    "common.refresh": "Atualizar",
    "common.viewProfile": "Ver Perfil",
    "common.shareProfile": "Compartilhar",
    "common.copied": "Copiado!",
    "common.founder": "Fundador e Admin",
    "common.coFounder": "Co-fundador e Admin",
    "common.developer": "Desenvolvedor",
    "common.backToTop": "Voltar ao topo",
    "common.apply": "Aplicar",

    "explore.badge": "Comunidade de Desenvolvedores",
    "explore.titlePrefix": "Descubra",
    "explore.titleHighlight": "Talentos",
    "explore.description": "Explore desenvolvedores e talentos no ecossistema Hey Coder'z.",
    "explore.totalMembers": "Total de Membros",
    "explore.management": "Gestão",
    "explore.searchPlaceholder": "Buscar por nome ou tecnologia...",
    "explore.filterAll": "Todos os Membros",
    "explore.filterAdmin": "Gestão e Fundadores",
    "explore.filterNew": "Novos Talentos",
    "explore.filterTopXp": "Mais XP",
    "explore.notFound": "Nenhum usuário encontrado",
    "explore.notFoundDesc": "Nenhum perfil correspondeu à busca.",

    "footer.desc": "Plataforma moderna para desenvolvedores.",
    "footer.navigation": "Navegação",
    "footer.ecosystem": "Ecossistema",
    "footer.legal": "Legal e Privacidade",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Uso",
    "footer.cookies": "Política de Cookies",
    "footer.copyright": "Todos os direitos reservados.",
  },

  az: {
    "nav.tools": "Alətlər",
    "nav.playground": "Playground",
    "nav.resources": "Resurslar",
    "nav.community": "İcma",
    "nav.explore": "Kəşf Et",
    "nav.blog": "Bloq",
    "nav.about": "Haqqımızda",
    "nav.login": "Daxil Ol",
    "nav.register": "Qeydiyyat",
    "nav.dashboard": "Panel & Profil",
    "nav.publicProfile": "İctimai Profil",
    "nav.settings": "Tənzimləmələr",
    "nav.logout": "Çıxış",
    "nav.langSelect": "Dil Seçimi",

    "hero.badge": "Kodla. Öyrən. İnkişaf et.",
    "hero.titlePrefix": "Tərtibatçılar üçün",
    "hero.titleBreak": "hər şey",
    "hero.titleHighlight": "buradadır.",
    "hero.subtitle": "Hey! Coder'z tərtibatçıların məhsuldarlığını artıran müasir alətlər, zəngin resurslar və icma dəstəyi təqdim edir.",
    "hero.exploreBtn": "İndi Kəşf Et",
    "hero.resourcesBtn": "Resurslara Bax",
    "trust.label": "TƏRTİBATÇILARIN ETİBAR ETDİYİ PLATFORMA",

    "common.search": "Axtar...",
    "common.save": "Yadda Saxla",
    "common.cancel": "Ləğv Et",
    "common.delete": "Sil",
    "common.edit": "Düzəliş Et",
    "common.loading": "Yüklənir...",
    "common.refresh": "Yenilə",
    "common.viewProfile": "Profilə Bax",
    "common.shareProfile": "Profili Paylaş",
    "common.copied": "Kopyalandı!",
    "common.founder": "Təsisçi & Admin",
    "common.coFounder": "Həmtəsisçi & Admin",
    "common.developer": "Tərtibatçı",
    "common.backToTop": "Yuxarı Qayıt",
    "common.apply": "Tətbiq Et",

    "explore.badge": "Tərtibatçı İcması & Vitrin",
    "explore.titlePrefix": "İstedadları",
    "explore.titleHighlight": "Kəşf Et",
    "explore.description": "Hey Coder'z ekosistemindəki bütün tərtibatçıları və istedadları kəşf edin.",
    "explore.totalMembers": "Ümumi Üzv",
    "explore.management": "Rəhbərlik",
    "explore.searchPlaceholder": "Ad, @istifadəçi və ya texnologiya axtar...",
    "explore.filterAll": "Bütün Üzvlər",
    "explore.filterAdmin": "Rəhbərlik & Təsisçilər",
    "explore.filterNew": "Yeni Qoşulanlar",
    "explore.filterTopXp": "Ən Yüksək XP",
    "explore.notFound": "İstifadəçi Tapılmadı",
    "explore.notFoundDesc": "Axtarışınıza uyğun tərtibatçı profili tapılmadı.",

    "footer.desc": "Tərtibatçıların məhsuldarlığını artıran müasir alətlər və icma platforması.",
    "footer.navigation": "Naviqasiya",
    "footer.ecosystem": "Ekosistem",
    "footer.legal": "Hüquqi & Məxfilik",
    "footer.privacy": "Məxfilik Siyasəti",
    "footer.terms": "İstifadə Şərtləri",
    "footer.cookies": "Kuki Siyasəti",
    "footer.copyright": "Bütün hüquqlar qorunur.",
  },

  nl: {
    "nav.tools": "Hulpmiddelen",
    "nav.playground": "Playground",
    "nav.resources": "Bronnen",
    "nav.community": "Gemeenschap",
    "nav.explore": "Ontdekken",
    "nav.blog": "Blog",
    "nav.about": "Over Ons",
    "nav.login": "Inloggen",
    "nav.register": "Registreren",
    "nav.dashboard": "Dashboard & Profiel",
    "nav.publicProfile": "Openbaar Profiel",
    "nav.settings": "Instellingen & Beveiliging",
    "nav.logout": "Uitloggen",
    "nav.langSelect": "Taalkeuze",

    "hero.badge": "Codeer. Leer. Groei.",
    "hero.titlePrefix": "Alles voor",
    "hero.titleBreak": "ontwikkelaars",
    "hero.titleHighlight": "is hier.",
    "hero.subtitle": "Hey! Coder'z verhoogt de productiviteit van ontwikkelaars met krachtige tools, bronnen en community-ondersteuning.",
    "hero.exploreBtn": "Nu Ontdekken",
    "hero.resourcesBtn": "Bekijk Bronnen",
    "trust.label": "HET VERTROUWDE ONTWIKKELAARSPLATFORM",

    "common.search": "Zoeken...",
    "common.save": "Opslaan",
    "common.cancel": "Annuleren",
    "common.delete": "Verwijderen",
    "common.edit": "Bewerken",
    "common.loading": "Laden...",
    "common.refresh": "Vernieuwen",
    "common.viewProfile": "Bekijk Profiel",
    "common.shareProfile": "Profiel Delen",
    "common.copied": "Gekopieerd!",
    "common.founder": "Oprichter & Admin",
    "common.coFounder": "Mede-oprichter & Admin",
    "common.developer": "Ontwikkelaar",
    "common.backToTop": "Naar boven",
    "common.apply": "Toepassen",

    "explore.badge": "Ontwikkelaarscommunity",
    "explore.titlePrefix": "Ontdek",
    "explore.titleHighlight": "Talenten",
    "explore.description": "Ontdek ontwikkelaars en oprichters in het Hey Coder'z-ecosysteem.",
    "explore.totalMembers": "Totaal Leden",
    "explore.management": "Beheer",
    "explore.searchPlaceholder": "Zoek op naam, @gebruiker of tech...",
    "explore.filterAll": "Alle Leden",
    "explore.filterAdmin": "Leiderschap & Oprichters",
    "explore.filterNew": "Nieuw Binnengekomen",
    "explore.filterTopXp": "Hoogste XP",
    "explore.notFound": "Geen gebruikers gevonden",
    "explore.notFoundDesc": "Geen profiel gevonden dat overeenkomt.",

    "footer.desc": "Modern ontwikkelaarsecosysteem voor tools en bronnen.",
    "footer.navigation": "Navigatie",
    "footer.ecosystem": "Ecosysteem",
    "footer.legal": "Juridisch & Privacy",
    "footer.privacy": "Privacybeleid",
    "footer.terms": "Algemene Voorwaarden",
    "footer.cookies": "Cookiebeleid",
    "footer.copyright": "Alle rechten voorbehouden.",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  currentLanguage: LanguageOption;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>("tr");

  useEffect(() => {
    try {
      const saved = (localStorage.getItem("heycoderz_language") ||
        localStorage.getItem("heycoderz_site_lang")) as LanguageCode;
      if (saved && DICTIONARY[saved]) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    try {
      localStorage.setItem("heycoderz_language", code);
      localStorage.setItem("heycoderz_site_lang", code);
    } catch {}
  };

  const currentLanguage = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const t = (key: string): string => {
    const langDict = DICTIONARY[language] || DICTIONARY.tr;
    return langDict[key] || DICTIONARY.tr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
