"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "tr" | "en" | "de" | "es" | "fr" | "ru" | "ar" | "zh" | "ja" | "pt" | "az" | "it";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "Chinese", nativeName: "简体中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan", flag: "🇦🇿" },
];

export const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  tr: {
    // Navigation
    "nav.tools": "Araçlar",
    "nav.playground": "Playground",
    "nav.resources": "Kaynaklar",
    "nav.community": "Topluluk",
    "nav.explore": "Keşfet",
    "nav.blog": "Blog",
    "nav.about": "Hakkımızda",
    "nav.login": "Giriş Yap",
    "nav.register": "Üye Ol",
    "nav.dashboard": "Dashboard & Profil",
    "nav.publicProfile": "Kamuya Açık Profil",
    "nav.settings": "Ayarlar & Güvenlik",
    "nav.logout": "Çıkış Yap",
    "nav.langSelect": "Dil Seçimi",

    // Common UI
    "common.search": "Ara...",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.loading": "Yükleniyor...",
    "common.refresh": "Yenile",
    "common.viewProfile": "Profili Gör",
    "common.shareProfile": "Profili Paylaş",
    "common.copied": "Kopyalandı!",
    "common.founder": "Kurucu & Admin",
    "common.coFounder": "Kurucu Ortak & Admin",
    "common.developer": "Geliştirici",
    "common.backToTop": "Yukarı Çık",
    "common.apply": "Uygula",

    // Kesfet Page
    "explore.badge": "Geliştirici Topluluğu & Vitrini",
    "explore.titlePrefix": "Yetenekleri",
    "explore.titleHighlight": "Keşfet",
    "explore.description": "Hey Coder'z ekosistemindeki tüm geliştiricileri, kurucuları ve yeni katılan yetenekleri keşfedin, profillerini inceleyin.",
    "explore.totalMembers": "Toplam Üye",
    "explore.management": "Yönetim",
    "explore.searchPlaceholder": "İsim, @kullanıcı veya teknoloji ara (örn: React)...",
    "explore.filterAll": "Tüm Üyeler",
    "explore.filterAdmin": "Yönetim & Kurucular",
    "explore.filterNew": "Yeni Katılanlar",
    "explore.filterTopXp": "En Yüksek XP",
    "explore.notFound": "Kullanıcı Bulunamadı",
    "explore.notFoundDesc": "Arama kriterinize uygun bir geliştirici profili bulunamadı.",

    // Footer
    "footer.desc": "Geliştiricilerin üretkenliğini artıran araçlar, kaynaklar ve modern geliştirici ekosistemi platformu.",
    "footer.navigation": "Navigasyon",
    "footer.ecosystem": "Ekosistem",
    "footer.legal": "Yasal & Gizlilik",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları",
    "footer.cookies": "Çerez Politikası",
    "footer.copyright": "Tüm hakları saklıdır.",
  },

  en: {
    // Navigation
    "nav.tools": "Tools",
    "nav.playground": "Playground",
    "nav.resources": "Resources",
    "nav.community": "Community",
    "nav.explore": "Explore",
    "nav.blog": "Blog",
    "nav.about": "About Us",
    "nav.login": "Sign In",
    "nav.register": "Sign Up",
    "nav.dashboard": "Dashboard & Profile",
    "nav.publicProfile": "Public Profile",
    "nav.settings": "Settings & Security",
    "nav.logout": "Log Out",
    "nav.langSelect": "Language",

    // Common UI
    "common.search": "Search...",
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.refresh": "Refresh",
    "common.viewProfile": "View Profile",
    "common.shareProfile": "Share Profile",
    "common.copied": "Copied!",
    "common.founder": "Founder & Admin",
    "common.coFounder": "Co-Founder & Admin",
    "common.developer": "Developer",
    "common.backToTop": "Back to Top",
    "common.apply": "Apply",

    // Kesfet Page
    "explore.badge": "Developer Community & Showcase",
    "explore.titlePrefix": "Discover",
    "explore.titleHighlight": "Talents",
    "explore.description": "Explore developers, founders, and emerging talents across the Hey Coder'z ecosystem.",
    "explore.totalMembers": "Total Members",
    "explore.management": "Management",
    "explore.searchPlaceholder": "Search by name, @username, or tech (e.g. React)...",
    "explore.filterAll": "All Members",
    "explore.filterAdmin": "Leadership & Founders",
    "explore.filterNew": "New Arrivals",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "No Users Found",
    "explore.notFoundDesc": "No developer profile matched your search criteria.",

    // Footer
    "footer.desc": "Tools, resources, and modern developer ecosystem platform empowering developer productivity.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Ecosystem",
    "footer.legal": "Legal & Privacy",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.copyright": "All rights reserved.",
  },

  de: {
    "nav.tools": "Werkzeuge",
    "nav.playground": "Playground",
    "nav.resources": "Ressourcen",
    "nav.community": "Community",
    "nav.explore": "Entdecken",
    "nav.blog": "Blog",
    "nav.about": "Über Uns",
    "nav.login": "Anmelden",
    "nav.register": "Registrieren",
    "nav.dashboard": "Dashboard & Profil",
    "nav.publicProfile": "Öffentliches Profil",
    "nav.settings": "Einstellungen & Sicherheit",
    "nav.logout": "Abmelden",
    "nav.langSelect": "Sprache",
    "common.search": "Suchen...",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.loading": "Wird geladen...",
    "common.refresh": "Aktualisieren",
    "common.viewProfile": "Profil ansehen",
    "common.shareProfile": "Profil teilen",
    "common.copied": "Kopiert!",
    "common.founder": "Gründer & Admin",
    "common.coFounder": "Mitgründer & Admin",
    "common.developer": "Entwickler",
    "common.backToTop": "Nach oben",
    "common.apply": "Anwenden",
    "explore.badge": "Entwickler-Community & Vitrine",
    "explore.titlePrefix": "Talente",
    "explore.titleHighlight": "Entdecken",
    "explore.description": "Entdecken Sie Entwickler, Gründer und neue Talente im Hey Coder'z-Ökosystem.",
    "explore.totalMembers": "Mitglieder gesamt",
    "explore.management": "Leitung",
    "explore.searchPlaceholder": "Nach Name, @Benutzer oder Technologie suchen...",
    "explore.filterAll": "Alle Mitglieder",
    "explore.filterAdmin": "Leitung & Gründer",
    "explore.filterNew": "Neu beigetreten",
    "explore.filterTopXp": "Höchste XP",
    "explore.notFound": "Benutzer nicht gefunden",
    "explore.notFoundDesc": "Kein Entwicklerprofil entsprach Ihren Suchkriterien.",
    "footer.desc": "Plattform für Entwicklerproduktivität mit modernen Tools, Ressourcen und Community.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Ökosystem",
    "footer.legal": "Rechtliches & Datenschutz",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.cookies": "Cookie-Richtlinie",
    "footer.copyright": "Alle Rechte vorbehalten.",
  },

  es: {
    "nav.tools": "Herramientas",
    "nav.playground": "Playground",
    "nav.resources": "Recursos",
    "nav.community": "Comunidad",
    "nav.explore": "Explorar",
    "nav.blog": "Blog",
    "nav.about": "Sobre Nosotros",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Registrarse",
    "nav.dashboard": "Panel y Perfil",
    "nav.publicProfile": "Perfil Público",
    "nav.settings": "Configuración y Seguridad",
    "nav.logout": "Cerrar Sesión",
    "nav.langSelect": "Idioma",
    "common.search": "Buscar...",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.refresh": "Actualizar",
    "common.viewProfile": "Ver Perfil",
    "common.shareProfile": "Compartir Perfil",
    "common.copied": "¡Copiado!",
    "common.founder": "Fundador y Admin",
    "common.coFounder": "Cofundador y Admin",
    "common.developer": "Desarrollador",
    "common.backToTop": "Volver Arriba",
    "common.apply": "Aplicar",
    "explore.badge": "Comunidad de Desarrolladores",
    "explore.titlePrefix": "Descubre",
    "explore.titleHighlight": "Talentos",
    "explore.description": "Explora desarrolladores, fundadores y nuevos talentos en el ecosistema Hey Coder'z.",
    "explore.totalMembers": "Total de Miembros",
    "explore.management": "Administración",
    "explore.searchPlaceholder": "Buscar por nombre, @usuario o tecnología...",
    "explore.filterAll": "Todos los Miembros",
    "explore.filterAdmin": "Liderazgo y Fundadores",
    "explore.filterNew": "Recién Llegados",
    "explore.filterTopXp": "Mayor XP",
    "explore.notFound": "Usuario no encontrado",
    "explore.notFoundDesc": "Ningún perfil de desarrollador coincidió con su búsqueda.",
    "footer.desc": "Plataforma de ecosistema para desarrolladores que impulsa la productividad con herramientas y recursos.",
    "footer.navigation": "Navegación",
    "footer.ecosystem": "Ecosistema",
    "footer.legal": "Legal y Privacidad",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Uso",
    "footer.cookies": "Política de Cookies",
    "footer.copyright": "Todos los derechos reservados.",
  },

  fr: {
    "nav.tools": "Outils",
    "nav.playground": "Playground",
    "nav.resources": "Ressources",
    "nav.community": "Communauté",
    "nav.explore": "Explorer",
    "nav.blog": "Blog",
    "nav.about": "À Propos",
    "nav.login": "Connexion",
    "nav.register": "S'inscrire",
    "nav.dashboard": "Tableau de Bord",
    "nav.publicProfile": "Profil Public",
    "nav.settings": "Paramètres & Sécurité",
    "nav.logout": "Déconnexion",
    "nav.langSelect": "Langue",
    "common.search": "Rechercher...",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.refresh": "Actualiser",
    "common.viewProfile": "Voir le Profil",
    "common.shareProfile": "Partager le Profil",
    "common.copied": "Copié !",
    "common.founder": "Fondateur & Admin",
    "common.coFounder": "Cofondateur & Admin",
    "common.developer": "Développeur",
    "common.backToTop": "Haut de Page",
    "common.apply": "Appliquer",
    "explore.badge": "Communauté de Développeurs",
    "explore.titlePrefix": "Découvrez les",
    "explore.titleHighlight": "Talents",
    "explore.description": "Découvrez les développeurs, fondateurs et nouveaux talents de l'écosystème Hey Coder'z.",
    "explore.totalMembers": "Total Membres",
    "explore.management": "Direction",
    "explore.searchPlaceholder": "Rechercher par nom, @pseudo ou techno...",
    "explore.filterAll": "Tous les Membres",
    "explore.filterAdmin": "Direction & Fondateurs",
    "explore.filterNew": "Nouveaux Arrivants",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "Utilisateur non trouvé",
    "explore.notFoundDesc": "Aucun profil de développeur ne correspond à vos critères.",
    "footer.desc": "Plateforme d'écosystème pour développeurs améliorant la productivité.",
    "footer.navigation": "Navigation",
    "footer.ecosystem": "Écosystème",
    "footer.legal": "Légal & Confidentialité",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.cookies": "Politique des Cookies",
    "footer.copyright": "Tous droits réservés.",
  },

  ru: {
    "nav.tools": "Инструменты",
    "nav.playground": "Песочница",
    "nav.resources": "Ресурсы",
    "nav.community": "Сообщество",
    "nav.explore": "Обзор",
    "nav.blog": "Блог",
    "nav.about": "О Нас",
    "nav.login": "Войти",
    "nav.register": "Регистрация",
    "nav.dashboard": "Панель управления",
    "nav.publicProfile": "Публичный профиль",
    "nav.settings": "Настройки и безопасность",
    "nav.logout": "Выйти",
    "nav.langSelect": "Язык",
    "common.search": "Поиск...",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.loading": "Загрузка...",
    "common.refresh": "Обновить",
    "common.viewProfile": "Открыть профиль",
    "common.shareProfile": "Поделиться профилем",
    "common.copied": "Скопировано!",
    "common.founder": "Основатель и Админ",
    "common.coFounder": "Сооснователь и Админ",
    "common.developer": "Разработчик",
    "common.backToTop": "Наверх",
    "common.apply": "Применить",
    "explore.badge": "Сообщество разработчиков",
    "explore.titlePrefix": "Откройте",
    "explore.titleHighlight": "Таланты",
    "explore.description": "Знакомьтесь с разработчиками, основателями и новыми талантами в Hey Coder'z.",
    "explore.totalMembers": "Всего участников",
    "explore.management": "Руководство",
    "explore.searchPlaceholder": "Поиск по имени, @username или технологии...",
    "explore.filterAll": "Все участники",
    "explore.filterAdmin": "Руководство",
    "explore.filterNew": "Новые участники",
    "explore.filterTopXp": "Больше всего XP",
    "explore.notFound": "Пользователь не найден",
    "explore.notFoundDesc": "По вашему запросу разработчики не найдены.",
    "footer.desc": "Платформа инструментов и сообщества для повышения продуктивности разработчиков.",
    "footer.navigation": "Навигация",
    "footer.ecosystem": "Экосистема",
    "footer.legal": "Правовая информация",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования",
    "footer.cookies": "Политика cookie",
    "footer.copyright": "Все права защищены.",
  },

  ar: {
    "nav.tools": "الأدوات",
    "nav.playground": "ساحة التجارب",
    "nav.resources": "المصادر",
    "nav.community": "المجتمع",
    "nav.explore": "استكشف",
    "nav.blog": "المدونة",
    "nav.about": "من نحن",
    "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب",
    "nav.dashboard": "لوحة التحكم",
    "nav.publicProfile": "الملف العام",
    "nav.settings": "الإعدادات والأمان",
    "nav.logout": "تسجيل الخروج",
    "nav.langSelect": "اللغة",
    "common.search": "بحث...",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.loading": "جاري التحميل...",
    "common.refresh": "تحديث",
    "common.viewProfile": "عرض الملف",
    "common.shareProfile": "مشاركة الملف",
    "common.copied": "تم النسخ!",
    "common.founder": "المؤسس والمدير",
    "common.coFounder": "شريك مؤسس ومدير",
    "common.developer": "مطور",
    "common.backToTop": "للأعلى",
    "common.apply": "تطبيق",
    "explore.badge": "مجتمع المطورين والمواهب",
    "explore.titlePrefix": "استكشف",
    "explore.titleHighlight": "المواهب",
    "explore.description": "اكتشف المطورين والمؤسسين والمواهب الصاعدة في مجتمع Hey Coder'z.",
    "explore.totalMembers": "إجمالي الأعضاء",
    "explore.management": "الإدارة",
    "explore.searchPlaceholder": "ابحث بالاسم أو التقنية...",
    "explore.filterAll": "جميع الأعضاء",
    "explore.filterAdmin": "الإدارة والمؤسسون",
    "explore.filterNew": "المنضمون حديثاً",
    "explore.filterTopXp": "الأعلى نقاطاً",
    "explore.notFound": "لم يتم العثور على مستخدم",
    "explore.notFoundDesc": "لا توجد نتائج تطابق معايير البحث الخاصة بك.",
    "footer.desc": "منصة أدوات ومصادر حديثة لزيادة إنتاجية المطورين.",
    "footer.navigation": "التنقل",
    "footer.ecosystem": "المنظومة",
    "footer.legal": "القانونية والخصوصية",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.cookies": "سياسة ملفات تعريف الارتباط",
    "footer.copyright": "جميع الحقوق محفوظة.",
  },

  zh: {
    "nav.tools": "工具箱",
    "nav.playground": "代码操场",
    "nav.resources": "资源中心",
    "nav.community": "开发者社区",
    "nav.explore": "探索",
    "nav.blog": "技术博客",
    "nav.about": "关于我们",
    "nav.login": "登录",
    "nav.register": "注册",
    "nav.dashboard": "控制台与主页",
    "nav.publicProfile": "公开主页",
    "nav.settings": "设置与安全",
    "nav.logout": "退出登录",
    "nav.langSelect": "语言选择",
    "common.search": "搜索...",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.loading": "加载中...",
    "common.refresh": "刷新",
    "common.viewProfile": "查看主页",
    "common.shareProfile": "分享主页",
    "common.copied": "已复制!",
    "common.founder": "创始人与管理员",
    "common.coFounder": "联合创始人",
    "common.developer": "开发者",
    "common.backToTop": "回到顶部",
    "common.apply": "应用",
    "explore.badge": "开发者社区与展示台",
    "explore.titlePrefix": "发现优秀",
    "explore.titleHighlight": "开发者",
    "explore.description": "探索 Hey Coder'z 生态系统中的所有开发者、创始人和新生代人才。",
    "explore.totalMembers": "总成员数",
    "explore.management": "管理团队",
    "explore.searchPlaceholder": "按姓名、用户名或技术栈搜索...",
    "explore.filterAll": "全部成员",
    "explore.filterAdmin": "管理团队与创始人",
    "explore.filterNew": "最新加入",
    "explore.filterTopXp": "最高经验值",
    "explore.notFound": "未找到用户",
    "explore.notFoundDesc": "没有找到符合您搜索条件的开发者主页。",
    "footer.desc": "提升开发者生产力的现代化工具、资源与社区生态平台。",
    "footer.navigation": "快速导航",
    "footer.ecosystem": "开发者生态",
    "footer.legal": "法律与隐私",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.cookies": "Cookie政策",
    "footer.copyright": "版权所有。",
  },

  ja: {
    "nav.tools": "ツール",
    "nav.playground": "プレイグラウンド",
    "nav.resources": "リソース",
    "nav.community": "コミュニティ",
    "nav.explore": "見つける",
    "nav.blog": "ブログ",
    "nav.about": "私たちについて",
    "nav.login": "ログイン",
    "nav.register": "新規登録",
    "nav.dashboard": "ダッシュボード",
    "nav.publicProfile": "公開プロフィール",
    "nav.settings": "設定とセキュリティ",
    "nav.logout": "ログアウト",
    "nav.langSelect": "言語切替",
    "common.search": "検索...",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.loading": "読み込み中...",
    "common.refresh": "更新",
    "common.viewProfile": "プロフィールを見る",
    "common.shareProfile": "プロフィールを共有",
    "common.copied": "コピーしました!",
    "common.founder": "創設者 & 管理者",
    "common.coFounder": "共同創設者",
    "common.developer": "開発者",
    "common.backToTop": "トップへ戻る",
    "common.apply": "適用",
    "explore.badge": "開発者コミュニティ & ショーケース",
    "explore.titlePrefix": "才能を",
    "explore.titleHighlight": "見つける",
    "explore.description": "Hey Coder'z のエンジニア、創設者、新メンバーを見つけよう。",
    "explore.totalMembers": "総メンバー数",
    "explore.management": "運営陣",
    "explore.searchPlaceholder": "名前、@ユーザー名、技術で検索...",
    "explore.filterAll": "すべてのメンバー",
    "explore.filterAdmin": "運営 & 創設者",
    "explore.filterNew": "新着メンバー",
    "explore.filterTopXp": "最高XP",
    "explore.notFound": "ユーザーが見つかりません",
    "explore.notFoundDesc": "条件に一致する開発者は見つかりませんでした。",
    "footer.desc": "開発者の生産性を高めるモダンなツールとコミュニティプラットフォーム。",
    "footer.navigation": "ナビゲーション",
    "footer.ecosystem": "エコシステム",
    "footer.legal": "規約とプライバシー",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.cookies": "Cookieポリシー",
    "footer.copyright": "全著作権所有。",
  },

  pt: {
    "nav.tools": "Ferramentas",
    "nav.playground": "Playground",
    "nav.resources": "Recursos",
    "nav.community": "Comunidade",
    "nav.explore": "Explorar",
    "nav.blog": "Blog",
    "nav.about": "Sobre Nós",
    "nav.login": "Entrar",
    "nav.register": "Cadastrar",
    "nav.dashboard": "Painel e Perfil",
    "nav.publicProfile": "Perfil Público",
    "nav.settings": "Configurações e Segurança",
    "nav.logout": "Sair",
    "nav.langSelect": "Idioma",
    "common.search": "Pesquisar...",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.loading": "Carregando...",
    "common.refresh": "Atualizar",
    "common.viewProfile": "Ver Perfil",
    "common.shareProfile": "Compartilhar Perfil",
    "common.copied": "Copiado!",
    "common.founder": "Fundador e Admin",
    "common.coFounder": "Cofundador e Admin",
    "common.developer": "Desenvolvedor",
    "common.backToTop": "Voltar ao Topo",
    "common.apply": "Aplicar",
    "explore.badge": "Comunidade de Desenvolvedores",
    "explore.titlePrefix": "Descubra",
    "explore.titleHighlight": "Talentos",
    "explore.description": "Explore desenvolvedores, fundadores e novos talentos no Hey Coder'z.",
    "explore.totalMembers": "Total de Membros",
    "explore.management": "Gestão",
    "explore.searchPlaceholder": "Buscar por nome, @usuario ou tecnologia...",
    "explore.filterAll": "Todos os Membros",
    "explore.filterAdmin": "Liderança e Fundadores",
    "explore.filterNew": "Recém-Chegados",
    "explore.filterTopXp": "Maior XP",
    "explore.notFound": "Usuário não encontrado",
    "explore.notFoundDesc": "Nenhum perfil correspondeu à sua pesquisa.",
    "footer.desc": "Plataforma de ecossistema para desenvolvedores que impulsiona a produtividade.",
    "footer.navigation": "Navegação",
    "footer.ecosystem": "Ecossistema",
    "footer.legal": "Legal e Privacidade",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Uso",
    "footer.cookies": "Política de Cookies",
    "footer.copyright": "Todos os direitos reservados.",
  },

  it: {
    "nav.tools": "Strumenti",
    "nav.playground": "Playground",
    "nav.resources": "Risorse",
    "nav.community": "Community",
    "nav.explore": "Esplora",
    "nav.blog": "Blog",
    "nav.about": "Chi Siamo",
    "nav.login": "Accedi",
    "nav.register": "Registrati",
    "nav.dashboard": "Dashboard e Profilo",
    "nav.publicProfile": "Profilo Pubblico",
    "nav.settings": "Impostazioni e Sicurezza",
    "nav.logout": "Esci",
    "nav.langSelect": "Lingua",
    "common.search": "Cerca...",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.delete": "Elimina",
    "common.edit": "Modifica",
    "common.loading": "Caricamento...",
    "common.refresh": "Aggiorna",
    "common.viewProfile": "Visualizza Profilo",
    "common.shareProfile": "Condividi Profilo",
    "common.copied": "Copiato!",
    "common.founder": "Fondatore & Admin",
    "common.coFounder": "Cofondatore & Admin",
    "common.developer": "Sviluppatore",
    "common.backToTop": "Torna su",
    "common.apply": "Applica",
    "explore.badge": "Community di Sviluppatori",
    "explore.titlePrefix": "Scopri i",
    "explore.titleHighlight": "Talenti",
    "explore.description": "Esplora sviluppatori, fondatori e nuovi talenti nell'ecosistema Hey Coder'z.",
    "explore.totalMembers": "Membri Totali",
    "explore.management": "Amministrazione",
    "explore.searchPlaceholder": "Cerca per nome, @username o tecnologia...",
    "explore.filterAll": "Tutti i Membri",
    "explore.filterAdmin": "Leadership & Fondatori",
    "explore.filterNew": "Nuovi Arrivi",
    "explore.filterTopXp": "Top XP",
    "explore.notFound": "Nessun utente trovato",
    "explore.notFoundDesc": "Nessun profilo trovato con questi criteri.",
    "footer.desc": "Piattaforma per sviluppatori per aumentare produttività e competenze.",
    "footer.navigation": "Navigazione",
    "footer.ecosystem": "Ecosistema",
    "footer.legal": "Note Legali & Privacy",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Termini di Servizio",
    "footer.cookies": "Cookie Policy",
    "footer.copyright": "Tutti i diritti riservati.",
  },

  az: {
    "nav.tools": "Alətlər",
    "nav.playground": "Playground",
    "nav.resources": "Mənbələr",
    "nav.community": "İcma",
    "nav.explore": "Kəşf Et",
    "nav.blog": "Bloq",
    "nav.about": "Haqqımızda",
    "nav.login": "Daxil Ol",
    "nav.register": "Qeydiyyat",
    "nav.dashboard": "İdarə Paneli & Profil",
    "nav.publicProfile": "Açıq Profil",
    "nav.settings": "Tənzimləmələr & Təhlükəsizlik",
    "nav.logout": "Çıxış",
    "nav.langSelect": "Dil Seçimi",
    "common.search": "Axtar...",
    "common.save": "Yadda Saxla",
    "common.cancel": "Ləğv Et",
    "common.delete": "Sil",
    "common.edit": "Redaktə Et",
    "common.loading": "Yüklənir...",
    "common.refresh": "Yenilə",
    "common.viewProfile": "Profilə Bax",
    "common.shareProfile": "Profili Paylaş",
    "common.copied": "Kopyalandı!",
    "common.founder": "Təsisçi & Admin",
    "common.coFounder": "Həmtəsisçi & Admin",
    "common.developer": "Tərtibatçı",
    "common.backToTop": "Yuxarı Qayıt",
    "common.apply": "Tətbiq Et",
    "explore.badge": "Tərtibatçı İcması & Vitrin",
    "explore.titlePrefix": "İstedadları",
    "explore.titleHighlight": "Kəşf Et",
    "explore.description": "Hey Coder'z ekosistemindəki bütün tərtibatçıları və istedadları kəşf edin.",
    "explore.totalMembers": "Ümumi Üzv",
    "explore.management": "Rəhbərlik",
    "explore.searchPlaceholder": "Ad, @istifadəçi və ya texnologiya axtar...",
    "explore.filterAll": "Bütün Üzvlər",
    "explore.filterAdmin": "Rəhbərlik & Təsisçilər",
    "explore.filterNew": "Yeni Qoşulanlar",
    "explore.filterTopXp": "Ən Yüksək XP",
    "explore.notFound": "İstifadəçi Tapılmadı",
    "explore.notFoundDesc": "Axtarışınıza uyğun tərtibatçı profili tapılmadı.",
    "footer.desc": "Tərtibatçıların məhsuldarlığını artıran müasir alətlər və icma platforması.",
    "footer.navigation": "Naviqasiya",
    "footer.ecosystem": "Ekosistem",
    "footer.legal": "Hüquqi & Məxfilik",
    "footer.privacy": "Məxfilik Siyasəti",
    "footer.terms": "İstifadə Şərtləri",
    "footer.cookies": "Kuki Siyasəti",
    "footer.copyright": "Bütün hüquqlar qorunur.",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  currentLanguage: LanguageOption;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>("tr");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("heycoderz_site_lang") as LanguageCode;
      if (saved && DICTIONARY[saved]) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    try {
      localStorage.setItem("heycoderz_site_lang", code);
    } catch {}
  };

  const currentLanguage = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const t = (key: string): string => {
    const langDict = DICTIONARY[language] || DICTIONARY.tr;
    return langDict[key] || DICTIONARY.tr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
